[build]
  command = "yarn build:docs"
  publish = "dist/static"
  ignore = "git diff --quiet HEAD^ HEAD docs/"

# [[redirects]]
#   from = "/*"
#   to = "/index.original.html"
#   status = 200

[functions]
  directory = "functions"