[build]
  command = "yarn build:docs"
  publish = "dist/docs-app"
  ignore = "git diff --quiet HEAD^ HEAD projects/docs-app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"