[build]
  command = "yarn build docs"
  publish = "dist/docs"
  ignore = "git diff --quiet HEAD^ HEAD docs netlify.toml .nvmrc"

[dev]
  command = "ng serve docs"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "docs/functions"