[build]
  command = "yarn build:docs"
  publish = "dist/docs"
  ignore = "git diff --quiet HEAD^ HEAD docs/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"