[build]
  command = "yarn build"
  publish = "dist/app-dev"
  ignore = "git diff --quiet HEAD^ HEAD projects/app-dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"