name: 🚀 Build, Release & Deploy

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-20.04
    outputs:
      skipped: ${{ steps.changelog.outputs.skipped }}
      tag_name: ${{ steps.changelog.outputs.tag }}
      version: ${{ steps.changelog.outputs.version }}
      release_notes: ${{ steps.changelog.outputs.clean_changelog }}
      artifacts-key: ${{ steps.artifacts-key.outputs.name }}
    steps:
      - uses: actions/checkout@v2
      - uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          pre-commit: ./tools/sync-versions.js
          git-user-name: github-actions
          git-user-email: github-actions@github.com
          release-count: 0
      - run: echo ::set-output name=name::release-artifacts
        id: artifacts-key

  build:
    needs: changelog
    if: ${{ needs.changelog.outputs.skipped == 'false' }}
    uses: ./.github/workflows/build.yml
    with:
      artifacts-key: ${{ needs.changelog.outputs.artifacts-key }}
      tag_name: ${{ needs.changelog.outputs.tag_name }}

  release:
    needs: [build, changelog]
    uses: ./.github/workflows/release.yml
    with:
      artifacts-key: ${{ needs.changelog.outputs.artifacts-key }}
      tag_name: ${{ needs.changelog.outputs.tag_name }}
      version: ${{ needs.changelog.outputs.version }}
      release_notes: ${{ needs.changelog.outputs.release_notes }}

  deploy:
    needs: [build, changelog]
    uses: ./.github/workflows/deploy.yml
    with:
      artifacts-key: ${{ needs.changelog.outputs.artifacts-key }}
      version: ${{ needs.changelog.outputs.version }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      token: ${{ secrets.GITHUB_TOKEN }}
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHAOSPAD_NGAOX }}
