name: 🚀 Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  release-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: node
          package-name: ngaox
