name: ngaox packages
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependicies
        run: yarn install --frozen-lockfile
      - name: build @ngaox/seo
        run: |
          yarn build:seo
      - name: build @ngaox/padup
        run: |
          yarn build:padup
          cp -R projects/padup dist/padup
      - name: Store dist folder 💾
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  publish-seo:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download stored dist folder
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish @ngaox/seo to npm
        id: publishSeo
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          package: dist/seo/package.json
      - name: Log version update
        if: steps.publishSeo.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publishSeo.outputs.old-version }} => ${{ steps.publishSeo.outputs.version }}"
      - name: Publish @ngaox/padup to npm
        id: publishPadUp
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          package: dist/padup/package.json
      - name: Log version update
        if: steps.publishPadUp.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publishPadUp.outputs.old-version }} => ${{ steps.publishPadUp.outputs.version }}"