name: ngaox packages
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependicies
          npm ci
      - name: build @ngaox/seo
        run: |
          npm run build:seo
      - name: build @ngaox/padup
        run: |
          npm run build:padup
          cp -R projects/padup dist/padup
      - name: Store dist folder 💾
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  publish-seo:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download stored dist folder
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish @ngaox/seo to npm
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          package: dist/seo/package.json
      - name: Publish @ngaox/padup to npm
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          package: dist/padup/package.json