name: 🧿 Main workflow
on:
  push:
    branches:
      - main
jobs:
  changelogs:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      upload_url: ${{ steps.release.outputs.upload_url }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
    steps:
      - uses: google-github-actions/release-please-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest-pr
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
