on:
  workflow_call:
    inputs:
      artifacts-key:
        required: true
        type: string
      tag_name:
        required: true
        type: string
      version:
        required: true
        type: string
      release_notes:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifacts-key }}
          path: dist

      - uses: softprops/action-gh-release@v1
        id: release
        with:
          name: 'ngaox-${{ inputs.tag_name }}'
          tag_name: ${{ inputs.tag_name }}
          body: ${{ inputs.release_notes }}
          files: |
            dist/artifacts/*
            LICENSE
